from google import genai
from dotenv import load_dotenv
import os
from pydantic import BaseModel

class plan_questions(BaseModel):
    questions: str

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

client = genai.Client(api_key=api_key)

def generate_response(query, results):
    # Build the context block from your retrieved Chroma documents
    context = "\n".join(results)  # Assuming you've already run collection.query()

    prompt = f""""You are an expert interview coach creating a personalized interview preparation plan for a candidate.\n\n"
        f"Candidate profile:\n{query}\n\n"
        "Below is a list of 10 relevant interview questions retrieved from a curated database. "
        "You must only work with these exact questions. Do NOT generate new questions.\n\n"
        f"{context}\n\n"
        "Your task:\n"
        "Select the most appropriate questions from the above list (only if suitable), and organize them into the following categories:\n"
        "1. Recruiter Screening Questions\n"
        "2. Hiring Manager Questions\n"
        "3. Onsite Interview Questions\n"
        "4. Final Round Interview Questions\n\n"
        "For each category, list up to 5 questions with a one-line coaching tip on how the candidate should approach it. "
        "If you cannot find good matches for a category, just leave it empty.\n\n"
        "Do not create new questions or hallucinate content.\n"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config={"response_mime_type": "application/json",
                "response_schema": str},
    ).parsed

    return response

"""r = ['Tell me why you will be a good fit for the position. Prioritization All Tech Interview Handbook STAR', 'development? general STAR General TBD Recruiter Screen Hiring Manager Junior', 'IC/Senior PM Google STAR Explore mentorship and leadership skills Behavioral Hiring Manager']
q ="You are a high level manager of the company. You are taking the interview of a candidate.The following is the summary generated by our system. Use it and grab the suitable questions from the databaseSanjeev Yadav, a Mumbai-based Information Technology engineering student, is a Software Developer at Quantal AI (11-50 employees) since March 2025.  He possesses skills in GitHub, Unit Testing, API Development, and Go, with certifications in Java, Python, SQL, and Web Development.  He is in the beginning stages of his career and exploring opportunities at Google, aiming for a broad search initially before refining his focus. His LinkedIn profile is available at [https://www.linkedin.com/in/sanjeev-yadav-7349861a3/](https://www.linkedin.com/in/sanjeev-yadav-7349861a3/"

print(generate_response(q, r))"""